name: a-varc
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _openmp_mutex=4.5=20_gnu
  - bzip2=1.0.8=hda65f42_9
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - icu=78.2=h33c6efd_0
  - ld_impl_linux-64=2.45.1=default_hbd61a6d_101
  - libexpat=2.7.4=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libgcc=15.2.0=he0feb66_18
  - libgcc-ng=15.2.0=h69a702a_18
  - libgomp=15.2.0=he0feb66_18
  - liblzma=5.8.2=hb03c661_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_18
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - pip=26.0.1=pyh8b19718_0
  - python=3.10.19=h3c07f61_3_cpython
  - readline=8.3=h853b02a_0
  - setuptools=82.0.0=pyh332efcf_0
  - tk=8.6.13=noxft_h366c992_103
  - tzdata=2025c=hc9c84f9_1
  - wheel=0.46.3=pyhd8ed1ab_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu126
      - annotated-doc==0.0.4
      - anyio==4.12.1
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.2.2
      - docstring-parser==0.17.0
      - exceptiongroup==1.3.1
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.4.1
      - idna==3.11
      - imagenetv2-pytorch @ git+https://github.com/modestyachts/ImageNetV2_pytorch
      - jinja2==3.1.6
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mypy-extensions==1.1.0
      - networkx==3.4.2
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.6.77
      - pillow==12.1.1
      - pygments==2.19.2
      - pyyaml==6.0.3
      - regex==2026.2.19
      - requests==2.32.5
      - rich==14.3.3
      - safetensors==0.7.0
      - shellingham==1.5.4
      - sympy==1.14.0
      - tokenizers==0.22.2
      - torch==2.10.0+cu126
      - torchvision==0.25.0+cu126
      - transformers==5.2.0
      - triton==3.6.0
      - typed-argument-parser==1.11.0
      - typer==0.24.1
      - typer-slim==0.24.0
      - typing-inspect==0.9.0
      - urllib3==2.6.3
prefix: /home/min/a/chen5262/disk_g/anaconda3/envs/a-varc
